### ISSUE TITLE
*ISSUE : 改进已被弃用的 rand.h 与仓库整理

### ISSUE THREAD

**Issue by BiDuang** [Grandpas-Daddies/GameTower#8]
阁下项目中在 `src/main.cpp` 中有使用 `rand()` 函数，而在 C++ 新标准中，此函数已不赞成使用。

推荐阁下将此函数弃用，更换为 `random` 库函数，此库函数可通过设备硬件噪声产生的随机数种子实现“真随机”。

[参考阅读](https://zh.cppreference.com/w/cpp/numeric/random)

另外，阁下项目中似乎没有添加 `.gitignore` 文件来忽略本地构建文件，这可能导致协作拉取代码时响应变慢。

稍后，一个 PR 将被提交，供您审阅。

祝安。

**Comment by hongjr03** [comment]
已 Merge，谢谢冰哥提醒😙
